### ISSUE TITLE
drush-install runs every time puppet runs

### ISSUE THREAD

**Issue by tdm4** [previousnext/puppet-drush#3]
Every time puppet runs, the drush-install component runs:

Info: Applying configuration version '1455273389'
Notice: /Stage[main]/Drush/Drush::Drush[drush8]/Exec[drush-install-8]/returns: executed successfully

Hiera:
```
classes:
  - composer
  - drush
drush:
  drush8:
    version:   '8'
    link_name: '/usr/local/bin/drush'
```
Should there be an onlyif/unless test in exec { "drush-install-${version}"?
